#on: push
#name: CI
#jobs:
#  phpunit:
#    runs-on: ubuntu-latest
#    container:
#      image: kirschbaumdevelopment/laravel-test-runner:8.1
#
#    services:
#      mysql:
#        image: mysql:5.7.22
#        env:
#          MYSQL_ROOT_PASSWORD: root
#          MYSQL_DATABASE: test
#        ports:
#          - 3388:3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
#
#    steps:
#      - uses: actions/checkout@v1
#        with:
#          fetch-depth: 1
#
#      - name: Install composer dependencies
#        run: |
#          composer update --ignore-platform-reqs
#
#      - name: Prepare Laravel Application
#        run: |
#          cp .env.ci .env
#          php artisan key:generate
#
#      - name: Run Testsuite
#        run: vendor/bin/phpunit tests/
